/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IRESOLUTION "i"
# define VAR_ITIME "a"
# define VAR_INTENSITY "v"

const char *gfx_frag =
 "#version 130\n"
 "uniform float a;"
 "uniform vec2 i;"
 "uniform float v;\n"
 "#define AA 1\n"
 "#define T.5\n"
 "const vec2 f=vec2(1.,0.);"
 "const float x=3.14159;"
 "float y;"
 "const float z=1.;"
 "float m=.5,s=1.;"
 "mat2 t(mat2 a)"
 "{"
   "return mat2(a[1][1],-a[1][0],-a[0][1],a[0][0])/(a[0][0]*a[1][1]-a[1][0]*a[0][1]);"
 "}\n"
 "#define rand(a0)fract(sin(dot(a0.xy,vec2(12.9898,78.233)))*43758.5453)\n"
 "#define blend(a)((6.*a-15.)*a+10.)*a*a*a\n"
 "#define interpolate(d,w00,w10,w01,w11)mix(mix(w00,w10,blend(d.x)),mix(w01,w11,blend(d.x)),blend(d.y))\n"
 "vec2 t(vec2 a,float f)"
 "{"
   "return vec2(-1.)+2.*vec2(rand(a+vec2(f+2.,f+1.)),rand(a+vec2(f+3.,f+4.)));"
 "}"
 "float d(vec2 a,float x)"
 "{"
   "return interpolate(fract(a),dot(t(floor(a),x),fract(a)),dot(t(floor(a).xy+f.xy,x),fract(a).xy-f.xy),dot(t(floor(a).xy+f.yx,x),fract(a).xy-f.yx),dot(t(floor(a).xy+f.xx,x),fract(a).xy-f.xx));"
 "}"
 "float d(vec2 a,float x,float y,float z,float f)"
 "{"
   "float i=0.,v=1.;"
   "for(float m=y;m<z;m=m*2.)"
     "i=v*d(m*a,x)+i,v=v*f;"
   "return i;"
 "}\n"
 "#define g(a,a0)(2.*rand(vec2(a,a0))-1.)\n"
 "#define perlin1d(a,seed)mix(g(floor(a),seed)*fract(a),dot(vec2(g(floor(a)+1.,seed)),vec2(fract(a),-1.)),blend(fract(a)))\n"
 "float t(float a,float x,float y,float z,float f)"
 "{"
   "float i=0.,v=1.;"
   "for(float m=y;m<z;m=m*2.)"
     "i=v*perlin1d(m*a,x)+i,v=v*f;"
   "return i;"
 "}\n"
 "#define Rx(x)mat3(c.xyyy,cos(x),sin(x),0.,-sin(x),cos(x))\n"
 "#define Ry(x)mat3(cos(x),0.,-sin(x),c.yxy,sin(x),0.,cos(x))\n"
 "#define Rz(x)mat3(cos(x),sin(x),0.,-sin(x),cos(x),c.yyyx)\n"
 "#define rotate(a,a0)Rz(-(a0).z)*Ry(-(a0).y)*Rx(-(a0).x)*(a)\n"
 "mat3 d(vec3 a)"
 "{"
   "vec3 f=cos(a),v=sin(a);"
   "mat3 i=mat3(f.y*f.x,f.x*v.z+f.z*v.x*v.y,v.x*v.z-f.x*f.z*v.y,-f.y*v.z,f.x*f.z-v.x*v.y*v.z,f.z*v.x+f.x*v.y*v.z,v.y,-f.y*v.x,f.x*f.y);"
   "return i;"
 "}\n"
 "#define sphere(a,a0)length(a)-(a0)\n"
 "#define box(a,a0)length(max(abs(a)-(a0),0.))\n"
 "float p(vec3 f,vec2 x)"
 "{"
   "vec2 a=abs(vec2(length(f.xz),f.y))-x;"
   "return min(max(a.x,a.y),0.)+length(max(a,0.))-.02;"
 "}"
 "float n(vec3 f,vec2 x)"
 "{"
   "vec2 a=abs(vec2(length(f.xz),f.y))-x;"
   "return min(max(a.x,a.y),0.)+length(max(a,0.));"
 "}\n"
 "#define sphere2(a,a0,a1)vec2(sphere(a,a0),a1)\n"
 "#define box2(a,a0,a1)vec2(box(a,a0),a1)\n"
 "#define plane2(a,a0,a1)vec2((a).z-(a0),a1)\n"
 "#define repeat(a,a0)mod(a,a0)-.5*a0\n"
 "#define add(a,a0)mix(a0,a,step((a).x,(a0).x))\n"
 "#define sub(a,a0)mix(a0,a,step((a).x,-(a0).x))\n"
 "float d(float x,float a,float y)"
 "{"
   "float f=exp(-y*x)+exp(-y*a);"
   "return-log(f)/y;"
 "}"
 "float n(float a,float x,float y)"
 "{"
   "float f=clamp(.5+.5*(x-a)/y,0.,1.);"
   "return mix(x,a,f)-y*f*(1.-f);"
 "}"
 "float p(float a,float f,float x)"
 "{"
   "return a=pow(a,x),f=pow(f,x),pow(a*f/(a+f),1./x);"
 "}"
 "vec2 r(vec2 a,vec2 f)"
 "{"
   "vec2 i=add(a,f);"
   "i.x=d(a.x,f.x,12.);"
   "return i;"
 "}"
 "vec2 w(vec2 a,vec2 f)"
 "{"
   "vec2 i=add(a,f);"
   "i.x=n(a.x,f.x,.1);"
   "return i;"
 "}"
 "vec2 e(vec2 a,vec2 f)"
 "{"
   "vec2 i=add(a,f);"
   "i.x=p(a.x,f.x,8.);"
   "return i;"
 "}"
 "vec3 h(vec3 f,float a)"
 "{"
   "float x=cos(a*f.y),z=sin(a*f.y);"
   "mat2 i=mat2(x,-z,z,x);"
   "f=vec3(i*f.xy,f.z);"
   "return f;"
 "}"
 "vec2 b(vec3 a,float x)"
 "{"
   "vec2 i=f.xy;"
   "float y=.04;"
   "i=add(i,vec2(box(a+f.yyx,vec3(.2,.2,.1)),x));"
   "vec3 z=vec3(mod(a.xy,y)-.5*y,a.z+1.);"
   "vec2 v=(a-z).xy;"
   "if(length(v)<.25)"
     "i=add(i,vec2(box(z,vec3(.2*y,.2*y,.1)),3.));"
   "float m=-box(z,y*f.xxy+.2*f.yyx);"
   "m=abs(m)+y*.2;"
   "i.x=min(i.x,m);"
   "return i;"
 "}"
 "vec2 b(vec3 x)"
 "{"
   "vec2 i=f.xy;"
   "x.x+=.8*t(x.z,a,1.,100.,.4);"
   "x.y+=.8*t(x.z,a,1.,100.,.4);"
   "i=add(i,vec2(n(x.yzx,vec2(.005,100.)),5.));"
   "return i;"
 "}"
 "vec2 e(vec3 x)"
 "{"
   "vec2 i=f.xy;"
   "x+=f.yxy+a*f.yxy;"
   "i=add(i,plane2(x,-1.,15.));"
   "vec3 y=vec3(mod(x.xy,z)-.5*z,x.z);"
   "vec2 m=(x-y).xy;"
   "float d=rand(m),s=rand(m+vec2(a-mod(a,T))),c=v;"
   "if(s<c&&d<.6&&mod(a,T)<.5*T)"
     "i=add(i,b(y));"
   "if(d<.2)"
     "{"
       "if(s<c)"
         "i=add(i,vec2(p((y+f.yyx).yzx,vec2(.2,.6)),7.));"
       "else"
         " i=add(i,vec2(p((y+f.yyx).yzx,vec2(.2,.6)),8.));"
     "}"
   "else"
     " if(d<.6)"
       "{"
         "if(s<c)"
           "i=add(i,b(y,7.));"
         "else"
           " i=add(i,b(y,6.));"
       "}"
   "float r=-box(y,z*f.xxx);"
   "r=abs(r)+z*.1;"
   "i.x=min(i.x,r);"
   "return i;"
 "}"
 "const float A=100.;"
 "const int R=3000;"
 "const float o=.0005;"
 "vec2 b(in vec3 a,in vec3 f,out vec3 x)"
 "{"
   "float y=0.;"
   "for(int i=0;i<R;++i)"
     "{"
       "x=a+y*f;"
       "vec2 v=e(x);"
       "if(v.x<o*y)"
         "return vec2(y,v.y);"
       "y+=v.x;"
       "if(y>A)"
         "return vec2(A,6.);"
     "}"
   "return vec2(A,6.);"
 "}"
 "const float l=.005;"
 "vec3 h(vec3 a)"
 "{"
   "float x=e(a).x;"
   "return normalize(vec3(e(a+l*f.xyy).x-x,e(a+l*f.yxy).x-x,e(a+l*f.yyx).x-x));"
 "}"
 "vec3 c(float a,float x)"
 "{"
   "vec3 f=vec3(207.,30.,102.)/255.,v=vec3(245.,194.,87.)/255.;"
   "mat3 i=d(x*vec3(1.1,1.3,1.5));"
   "return 1.1*mix(abs(i*f),abs(i*v),a);"
 "}"
 "float b(vec2 a,vec2 f,vec2 x,float y)"
 "{"
   "float i=z;"
   "vec2 v=x-f,m=normalize(v),s=vec2(m.y,-m.x);"
   "mat2 d=mat2(m,s),c=t(d);"
   "vec2 p=c*f,w=c*x,b=c*a;"
   "float r=length(v),A=smoothstep(p.y+i/2.-3.*y,p.y+i/2.-y,b.y+r)*(1.-smoothstep(p.y+i/2.+y,p.y+i/2.+3.*y,b.y+r))*smoothstep(-3.*y,-y,b.x+.5*r)*(1.-smoothstep(y,3.*y,b.x-.5*r));"
   "return A;"
 "}"
 "float u(vec2 a,float f)"
 "{"
   "return 1.-step(length(a),f);"
 "}"
 "vec3 c(vec3 x,vec3 v,float i)"
 "{"
   "if(i<0.)"
     "return f.yyy;"
   "vec3 m=f.yyy,s=h(v),d=vec3(10.,0.,0.),p=normalize(d-v),w=normalize(reflect(-p,s)),r=normalize(x-v);"
   "if(i<=0.)"
     ";"
   "else"
     " if(i<=2.)"
       "m+=c(5.*v.z,62.2),m+=c(5.*v.z,65.2)*(pow(dot(w,r),2.)+2.4*dot(p,s));"
     "else"
       " if(i<=3.)"
         "m+=c(8.*v.z,9.6),m+=2.*c(8.*v.z,14.6)*(pow(dot(w,r),2.)+2.1*dot(p,s));"
       "else"
         " if(i<=4.)"
           "m+=c(8.*v.z,79.64),m+=2.*c(8.*v.z,84.64)*(pow(dot(w,r),2.)+2.1*dot(p,s));"
         "else"
           " if(i<=5.)"
             "m=f.xxx;"
           "else"
             " if(i<=6.)"
               "m+=.2*f.xxx,m+=.2*f.xxx*(pow(dot(w,r),6.)+10.2*dot(p,s)),m*=.5;"
             "else"
               " if(i<=7.)"
                 "m+=.2*f.xyy,m+=.2*f.xyy*(pow(dot(w,r),6.)+10.2*dot(p,s));"
               "else"
                 " if(i<=8.)"
                   "m+=.3*f.yxy+.1*f.xyx,m+=.5*f.yxy*(pow(dot(w,r),6.)+10.2*dot(p,s));"
                 "else"
                   " if(i<=9.)"
                     "m+=c(12.*v.z,60.3),m+=c(12.*v.z,65.3)*(pow(dot(w,r),2.)+1.9*dot(p,s));"
                   "else"
                     " if(i<=10.)"
                       "m+=c(v.z,140.71),m+=c(v.z,131.71)*(pow(dot(w,r),2.)+2.9*dot(p,s));"
                     "else"
                       " if(i<=11.)"
                         "m+=c(8.*v.z,177.76),m+=c(8.*v.z,182.76)*(pow(dot(w,r),2.)+1.9*dot(p,s));"
                       "else"
                         " if(i<=12.)"
                           "m+=c(23.*v.z,179.5),m+=c(23.*v.z,184.5)*(pow(dot(w,r),2.)+2.9*dot(p,s));"
                         "else"
                           " if(i<=13.)"
                             "m+=f.xxx*pow(dot(w,r),5.);"
                           "else"
                             " if(i<=14.)"
                               "{"
                                 "float A=z,l=.01;"
                                 "vec2 R=mod(v.xy,A);"
                                 "float o=max(smoothstep(A/2.-3.*l,A/2.-l,R.x)*(1.-smoothstep(A/2.+l,A/2.+3.*l,R.x)),smoothstep(A/2.-3.*l,A/2.-l,R.y)*(1.-smoothstep(A/2.+l,A/2.+3.*l,R.y)));"
                                 "m+=mix(f.yyy,c(.5+.5*sin(.3*length(v.xy-10.*f.yx)-5.*y),a),o);"
                               "}"
                             "else"
                               " if(i<=15.)"
                                 "{"
                                   "vec3 A=v;"
                                   "A+=f.yxy+a*f.yxy;"
                                   "vec3 R=vec3(mod(A.xy,z)-.5*z,A.z);"
                                   "vec2 l=(A-R).xy;"
                                   "float n=0.,o=.04,e=rand(l);"
                                   "if(e>=.2&&e<.6)"
                                     "{"
                                       "e=rand(l+z*f.xy);"
                                       "if(e>=.2&&e<.6||e>.7)"
                                         "{"
                                           "vec2 t=vec2(R.x,mod(R.y,o)-.5*o),u=1./o*(R.xy-t);"
                                           "if(abs(u.y-R.y)<3.)"
                                             "n=max(n,b(t-.5*z,z*f.xy,f.yy,.005));"
                                         "}"
                                       "e=rand(l-z*f.xy);"
                                       "if(e>=.2&&e<.6||e>.7)"
                                         "{"
                                           "vec2 t=vec2(R.x,mod(R.y,o)-.5*o),u=1./o*(R.xy-t);"
                                           "if(abs(u.y-R.y)<3.)"
                                             "n=max(n,b(t+.5*z,-z*f.xy,f.yy,.005));"
                                         "}"
                                       "e=rand(l+z*f.yx);"
                                       "if(e>=.2&&e<.6||e>.7)"
                                         "{"
                                           "vec2 t=vec2(mod(R.x,o)-.5*o,R.y),u=1./o*(R.xy-t);"
                                           "if(abs(u.x-R.x)<3.)"
                                             "n=max(n,b(t-.5*z,-z*f.yx,f.yy,.005));"
                                         "}"
                                       "e=rand(l-z*f.yx);"
                                       "if(e>=.2&&e<.6||e>.7)"
                                         "{"
                                           "vec2 t=vec2(mod(R.x,o)-.5*o,R.y),u=1./o*(R.xy-t);"
                                           "if(abs(u.x-R.x)<3.)"
                                             "n=max(n,b(t+.5*z,z*f.yx,f.yy,.005));"
                                         "}"
                                     "}"
                                   "m=n*f.yxy*(.75+.25*sin(5.*a));"
                                 "}"
   "float l=length(x-v);"
   "m=mix(m,mix(f.xyy,f.yyx,.5+.3*sin(6.*a)),clamp(1.-l,0.,1.));"
   "return m;"
 "}"
 "vec3 F(float a,vec2 x)"
 "{"
   "y=a;"
   "vec3 v=f.yyx-f.yxy,m=f.yyy,s=f.xyy,d=normalize(cross(m-v,-s)),r=f.yyy;"
   "\n#if AA!=1\n"
   "for(int e=0;e<AA;++e)"
     "for(int p=0;p<AA;++p)"
       "{"
         "vec2 z=vec2(float(e),float(p))/float(AA)-.5,A=(-i.xy+2.*(x+z))/i.y;"
         "\n#else\n"
         "vec2 R=(-i.xy+2.*x)/i.y;"
         "\n#endif\n"
         "vec3 w=normalize(m+R.x*s+R.y*d-v),o;"
         "vec2 u=b(v,w,o);"
         "r+=c(v,o,u.y);"
         "\n#if AA!=1\n"
       "}"
   "r/=float(AA*AA);"
   "\n#else\n"
   "\n#endif\n"
   "return r;"
 "}"
 "void C(out vec4 i,in vec2 f)"
 "{"
   "vec3 x=F(a,f);"
   "i=vec4(x,1.);"
 "}"
 "void main()"
 "{"
   "C(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
