/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IPROGRESS "y"
# define VAR_IRESOLUTION "v"
# define VAR_ITIME "x"

const char *gfx_frag =
 "#version 130\n"
 "uniform float y,x;"
 "uniform vec2 v;"
 "const float s=acos(-1.);"
 "const vec2 f=vec2(1.,0.);"
 "float m;"
 "float p(vec2 f)"
 "{"
   "return-1.+2.*fract(sin(dot(f.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float n(vec3 f)"
 "{"
   "return.33333*(p(f.xy)+p(f.yz)+p(f.zx));"
 "}"
 "float t(float v)"
 "{"
   "float m=floor(v);"
   "v=fract(v);"
   "float y=p(m*f.xx),s=p((m+1.)*f.xx);"
   "return mix(y,s,smoothstep(0.,1.,v));"
 "}"
 "float e(vec2 v)"
 "{"
   "vec2 x=floor(v);"
   "v=fract(v);"
   "float y=p(x),s=p(x+f.yx),m=p(x+f.xy),o=p(x+f.xx);"
   "return mix(mix(y,s,smoothstep(0.,1.,v.y)),mix(m,o,smoothstep(0.,1.,v.y)),smoothstep(0.,1.,v.x));"
 "}"
 "float h(vec3 v)"
 "{"
   "vec3 x=floor(v);"
   "v=fract(v);"
   "float y=n(x),s=n(x+f.xyy),m=n(x+f.yxy),o=n(x+f.yyx),p=n(x+f.xxy),i=n(x+f.yxx),l=n(x+f.xyx),c=n(x+f.xxx);"
   "return mix(mix(mix(y,o,smoothstep(0.,1.,v.z)),mix(s,l,smoothstep(0.,1.,v.z)),smoothstep(0.,1.,v.x)),mix(mix(m,i,smoothstep(0.,1.,v.z)),mix(p,c,smoothstep(0.,1.,v.z)),smoothstep(0.,1.,v.x)),smoothstep(0.,1.,v.y));"
 "}"
 "float e(vec2 x,float m,float y,float f)"
 "{"
   "float v=0.,s=1.2;"
   "for(float r=m;r<y;r=r*2.)"
     "v=s*e(r*x)+v,s=s*f;"
   "return v;"
 "}"
 "float h(vec3 x,float m,float y,float f)"
 "{"
   "float v=0.,s=1.;"
   "for(float r=m;r<y;r=r*2.)"
     "v=s*h(r*x)+v,s=s*f;"
   "return v;"
 "}"
 "float e(vec2 v,float m,float y,float s,float x)"
 "{"
   "float f=length(v),r=acos(v.x/f)*step(0.,v.y)-acos(v.x/f)*step(v.y,0.);"
   "r=clamp(r,s,x);"
   "vec2 z=m*vec2(cos(r),sin(r));"
   "return length(v-z)-y;"
 "}"
 "float n(vec2 v,vec2 y,vec2 m,float x)"
 "{"
   "vec2 f=m-y;"
   "return length(v-mix(y,m,clamp(dot(v-y,f)/dot(f,f),0.,1.)))-x;"
 "}"
 "void e(in int x,out float y,out float v,out vec2 s,out float m,out float r)"
 "{"
   "y=55.*p(float(-x)*f.xx),v=.002*sin(-3.*float(x)+12.*p(float(x)*f.xx)),s=2.*vec2(p(float(x)*f.xx),p(float(x+1)*f.xx)),m=pow(.5,float(x))*(1.+.1*p(float(x)*f.xx))*50.,r=1.2*mod(float(x*3),2.5)*p(vec2(float(x+4)));"
 "}"
 "float e(vec2 v,int x)"
 "{"
   "float f=0.,s,y,r,p;"
   "vec2 o;"
   "for(int i=0;i<x;++i)"
     "{"
       "e(i,s,p,o,y,r);"
       "float l=dot(o,v);"
       "f+=p*sin(-12.*y*l+r*m);"
     "}"
   "return f;"
 "}"
 "vec2 r(vec2 x)"
 "{"
   "vec2 y=vec2(n(x,vec2(-.5,-.4),vec2(v.x/v.y,-.4),.05),1.),f=vec2(n(x,vec2(-.5,-.4),vec2(v.x/v.y,-.4),.02),2.);"
   "return mix(y,f,step(1.,f.x));"
 "}"
 "vec2 w(vec3 x)"
 "{"
   "return x+=f.xyy*.05*m,vec2(x.z+.5-.5*e(x.xy,.9,1.,.1)+.05*e(x.xy,120.,180.,1.7),1.);"
 "}"
 "vec2 i(vec3 x)"
 "{"
   "x+=f.xxy*14.+f.yxy*.05*m;"
   "float y=-.5*e(x.xy,.9,1.,.1);"
   "if(x.z>-.46)"
     "y+=.05*e(x.xy,120.,180.,1.7);"
   "vec2 v=vec2(x.z+y,1.),s=vec2(x.z+.5-e(x.xy,22),2.);"
   "return mix(v,s,step(s.x,v.x));"
 "}"
 "vec2 d(vec3 x)"
 "{"
   "if(m<2.)"
     "return w(x);"
   "else"
     " if(m<4000.)"
       "return i(x);"
 "}"
 "const float l=.0001;"
 "vec3 a(vec3 x)"
 "{"
   "float y=d(x).x;"
   "return normalize(vec3(d(x+l*f.xyy).x-y,d(x+l*f.yxy).x-y,d(x+l*f.yyx).x-y));"
 "}"
 "vec3 o(vec2 v)"
 "{"
   "v+=.01*x*f.yx;"
   "vec2 y=mod(v,.05)-.025,s=v-y;"
   "float r=.17*exp(-.2*m);"
   "return.15*f.xxx+mix(.4*f.xyy,.8*f.xxy,1.-2.*v.y-length(v))*exp(-.2*m)+f.xxx*smoothstep(r+.01,r-.01,length(v))+2.*tanh(.2*m)*smoothstep(.003,-.003,length(y-.02*vec2(p(s),p(.1*s+.1*f.xx)))-.002*p(.1*s))*(.2*vec3(p(.1*s),p(.1*s+.1*f.xx),p(s+.3*f.xx))+.8)+(.2+.1*e(v+cos(.5*m)*sin(.5*v.x)*sin(.6*v.y),2.5,100.,.55))*exp(-.05*m);"
 "}"
 "float c(float v)"
 "{"
   "return smoothstep(v-1.,v,x)*(1.-smoothstep(v+5.,v+6.,x));"
 "}"
 "void a(out vec4 v,in vec2 y,float s)"
 "{"
   "m=s;"
   "vec2 r;"
   "vec3 p,z=.5+.5*e(f.yy,.9,1.,.1)-f.yxy+.5*f.yyx,n=.25*f.yyx,l=f.xyy,i=f.yyx,c=n+l*y.x+i*y.y,t=normalize(c-z);"
   "float w=0.,u=0.,g=0.;"
   "for(int b=0;b<200;++b)"
     "{"
       "p=z+w*t;"
       "r=d(p);"
       "if(r.x<.0002)"
         "break;"
       "if(w>15.||b==199)"
         "{"
           "v=vec4(mix(o(y),f.xxx,u/g),1.);"
           "return;"
         "}"
       "w+=r.x;"
       "g+=.5;"
       "u+=smoothstep(0.,1.5,p.z)*h(z+g*t,1.,100.,.35);"
     "}"
   "vec3 b=a(p),F=f.yxy,C=p+f.yyx,k=normalize(p-z),Z=normalize(reflect(-F,b)),Y=normalize(reflect(-C,b)),X;"
   "if(r.y==1.)"
     "X=.01*f.xyy*dot(F,b)+.2*f.xxx*pow(abs(dot(Z,k)),4.)+(.05*f.xyy+.05*f.yxy)*pow(abs(dot(Z,k)),2.),X*=exp(-.2*x);"
   "else"
     " if(r.y==2.)"
       "X=.4*f.xxx*dot(C,b)+.2*f.xxx*pow(abs(dot(Y,k)),2.);"
   "X=mix(X,.15*f.xxx,cosh(-2.*p.z)*tanh(.109*p.y));"
   "v=vec4(X,1.);"
 "}"
 "void a(out vec4 y,in vec2 p)"
 "{"
   "vec2 i=p/v.yy-.5,o;"
   "vec4 d,z,l;"
   "a(d,i,x);"
   "a(z,i,x+.01);"
   "y=.333*(d+z);"
   "vec3 X=y.xyz;"
   "o=r(i);"
   "float b=step(o.x,0.)*c(5.);"
   "if(o.y==1.)"
     "X=mix(X,mix(X,f.xxx,.1),b);"
   "vec2 w=i+(.01*x-.12)*f.yx;"
   "float t=atan(abs(w.y/w.x)),k=length(w);"
   "X+=1.4*(.5+.25*sin(2.3*s*t)+.25*sin(4.*s*t)+.25*sin(1.5*s*t))*exp(-3.*k)*f.xxx*exp(-.9*m)*(1.-smoothstep(1.4,1.6,x));"
   "float g=n(i,vec2(-.45,-.43),vec2(-.45,-.37),.005);"
   "g=min(g,n(i,vec2(-.43,-.37),vec2(-.47,-.37),.005));"
   "g=min(g,n(i,vec2(-.41,-.43),vec2(-.41,-.37),.005));"
   "g=min(g,n(i,vec2(-.41,-.4),vec2(-.37,-.4),.005));"
   "g=min(g,n(i,vec2(-.37,-.43),vec2(-.37,-.37),.005));"
   "g=min(g,n(i,vec2(-.35,-.43),vec2(-.35,-.37),.005));"
   "g=min(g,n(i,vec2(-.35,-.43),vec2(-.31,-.43),.005));"
   "g=min(g,n(i,vec2(-.35,-.4),vec2(-.33,-.4),.005));"
   "g=min(g,n(i,vec2(-.35,-.37),vec2(-.31,-.37),.005));"
   "g=min(g,n(i,vec2(-.25,-.37),vec2(-.23,-.37),.005));"
   "g=min(g,e(i-vec2(-.25,-.385),.015,.005,.5*s,1.5*s));"
   "g=min(g,e(i-vec2(-.25,-.385),.015,.005,-2.5*s,-.5*s));"
   "g=min(g,n(i,vec2(-.25,-.4),vec2(-.24,-.4),.005));"
   "X=mix(X,.8*f.xxx,c(5.)*smoothstep(.002,-.002,g));"
   "y=vec4(X,1.);"
 "}"
 "void main()"
 "{"
   "a(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
