/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_

const char *gfx_frag =
 "#version 130\n"
 "uniform float iTime;"
 "uniform vec2 iResolution;"
 "const float pi=acos(-1.);"
 "const vec3 c=vec3(1.,0.,-1.);"
 "vec2 vi;"
 "float t;\n"
 "#define T.5\n"
 "float rand(vec2 v)"
 "{"
   "return-1.+2.*fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float rand3(vec3 v)"
 "{"
   "return.33333*(rand(v.xy)+rand(v.yz)+rand(v.zx));"
 "}"
 "float dist(vec2 y,vec2 m,vec2 x,vec2 v,float i)"
 "{"
   "return i=clamp(i,0.,1.),length(v-pow(1.-i,2.)*y-2.*(1.-i)*i*m-i*i*x);"
 "}"
 "float dsp(vec2 v,vec2 m,vec2 y,vec2 x)"
 "{"
   "vec2 i=x-v,f=y-2.*m+v,s=m-v;"
   "vec3 r=vec3(3.*dot(s,f),2.*dot(s,s)-dot(i,f),-dot(i,s))/dot(f,f);"
   "float d=r.x/3.,p=r.y-d*r.x,a=-d*(d*d+p)+r.z,z=a*a/4.+p*p*p/27.;"
   "if(z>0.)"
     "{"
       "vec2 l=-.5*a*c.xx+sqrt(z)*c.xz,n=sign(l)*pow(abs(l),c.xx/3.);"
       "return dist(v,m,y,x,n.x+n.y-d);"
     "}"
   "float e=sqrt(-4./3.*p),l=acos(-.5*a*sqrt(-27./p/p/p))/3.;"
   "vec3 n=c.zxz*e*cos(l*c.xxx+c*pi/3.)-d;"
   "return min(dist(v,m,y,x,n.x),min(dist(v,m,y,x,n.y),dist(v,m,y,x,n.z)));"
 "}"
 "float dist(vec3 y,vec3 m,vec3 x,vec3 v,float i)"
 "{"
   "return i=clamp(i,0.,1.),length(v-pow(1.-i,2.)*y-2.*(1.-i)*i*m-i*i*x);"
 "}"
 "float worm(vec3 v,vec3 m,vec3 y,vec3 x)"
 "{"
   "vec3 i=x-v,f=y-2.*m+v,s=m-v,r=vec3(3.*dot(s,f),2.*dot(s,s)-dot(i,f),-dot(i,s))/dot(f,f);"
   "float d=r.x/3.,p=r.y-d*r.x,a=-d*(d*d+p)+r.z,l=a*a/4.+p*p*p/27.;"
   "if(l>0.)"
     "{"
       "vec2 z=-.5*a*c.xx+sqrt(l)*c.xz,n=sign(z)*pow(abs(z),c.xx/3.);"
       "return dist(v,m,y,x,n.x+n.y-d)-(.03+.01*mod(t,T)/T-.005*cos(1.7*pi*(n.x+n.y-d))+.01*abs(sin(2.*pi*10.*(n.x+n.y-d))));"
     "}"
   "float e=sqrt(-4./3.*p),n=acos(-.5*a*sqrt(-27./p/p/p))/3.;"
   "vec3 o=c.zxz*e*cos(n*c.xxx+c*pi/3.)-d;"
   "return min(dist(v,m,y,x,o.x)-(.03+.01*mod(iTime,T)/T-.005*cos(1.7*pi*o.x)+.01*abs(sin(2.*pi*10.*o.x))),min(dist(v,m,y,x,o.y)-(.03+.01*mod(iTime,T)/T-.005*cos(1.7*pi*o.y)+.01*abs(sin(2.*pi*10.*o.y))),dist(v,m,y,x,o.z)-(.03+.01*mod(iTime,T)/T-.005*cos(1.7*pi*o.z)+.01*abs(sin(2.*pi*10.*o.z)))));"
 "}"
 "float dsg(vec2 v,vec2 y,vec2 x)"
 "{"
   "vec2 i=y-v;"
   "float s=clamp(dot(x-v,i)/dot(i,i),0.,1.);"
   "return length(x-mix(v,y,s));"
 "}"
 "float smoothstep_noise1d(float v)"
 "{"
   "float i=floor(v);"
   "v=fract(v);"
   "float y=rand(i*c.xx),x=rand((i+1.)*c.xx);"
   "return mix(y,x,smoothstep(0.,1.,v));"
 "}"
 "float smoothstep_noise2d(vec2 v)"
 "{"
   "vec2 x=floor(v);"
   "v=fract(v);"
   "float i=rand(x),y=rand(x+c.yx),f=rand(x+c.xy),s=rand(x+c.xx);"
   "return mix(mix(i,y,smoothstep(0.,1.,v.y)),mix(f,s,smoothstep(0.,1.,v.y)),smoothstep(0.,1.,v.x));"
 "}"
 "float mfsmoothstep_noise2d(vec2 x,float v,float y,float i)"
 "{"
   "float m=0.,s=1.2;"
   "for(float f=v;f<y;f=f*2.)"
     "m=s*smoothstep_noise2d(f*x)+m,s=s*i;"
   "return m;"
 "}"
 "float cs(vec2 v,float x,float y,float s,float i)"
 "{"
   "float f=length(v),r=acos(v.x/f)*step(0.,v.y)-acos(v.x/f)*step(v.y,0.);"
   "r=clamp(r,s,i);"
   "vec2 d=x*vec2(cos(r),sin(r));"
   "return length(v-d)-y;"
 "}"
 "float b(vec2 v,vec2 i,vec2 y,float x)"
 "{"
   "vec2 s=y-i;"
   "return length(v-mix(i,y,clamp(dot(v-i,s)/dot(s,s),0.,1.)))-x;"
 "}"
 "void wave(in int x,out float y,out float v,out vec2 s,out float i,out float f)"
 "{"
   "y=55.*rand(float(-x)*c.xx),v=.00012*pow(.9,float(x-1))*rand(float(x)*c.xx),s=c.yx*rand(float(x)*c.xx)+.3*c.xy*rand(float(x)*c.xy),i=pow(.5+.1*rand(float(x+1)*c.xx),float(x))*(1.+.2*rand(float(x)*c.xx))*700.,f=12.*mod(float(x*3),2.5)*rand(vec2(float(x+4)));"
 "}"
 "float gerst(vec2 x,int i)"
 "{"
   "float v=0.,y,s,f,m;"
   "vec2 d;"
   "for(int r=0;r<i;++r)"
     "{"
       "wave(r,y,m,d,s,f);"
       "float p=dot(d,x);"
       "v+=m*sin(s*p+f*t);"
     "}"
   "return v;"
 "}"
 "vec3 vor(vec2 v)"
 "{"
   "v+=12.;"
   "vec2 i=floor(v);"
   "float x=1.;"
   "vec2 s=c.yy,f;"
   "float y=100.,r;"
   "vec3 m=c.xyy*100.;"
   "for(float d=-2.;d<=2.;d+=1.)"
     "for(float e=-2.;e<=2.;e+=1.)"
       "f=i+vec2(d,e),f+=rand(f),r=length(v-f),m=mix(m,vec3(r,f),step(r,m.x));"
   "for(float d=-2.;d<=2.;d+=1.)"
     "for(float e=-2.;e<=2.;e+=1.)"
       "{"
         "f=i+vec2(d,e);"
         "f+=rand(f);"
         "vec2 p=f-m.yz;"
         "r=dot(.5*p-v+m.yz,p)/length(p);"
         "x=min(x,r);"
       "}"
   "return vec3(x,s);"
 "}"
 "vec3 rot(vec3 y,vec3 v)"
 "{"
   "vec3 i=cos(v),s=sin(v);"
   "return mat3(i.x,0.,s.x,0.,1.,0.,-s.x,0.,i.x)*mat3(1.,0.,0.,0.,i.y,-s.y,0.,s.y,i.y)*mat3(i.z,-s.z,0.,s.z,i.z,0.,0.,0.,1.)*y;"
 "}"
 "vec2 z10presents(vec2 v)"
 "{"
   "vec2 i=vec2(b(v,vec2(-.5,-.4),vec2(iResolution.x/iResolution.y,-.4),.05),1.),y=vec2(b(v,vec2(-.5,-.4),vec2(iResolution.x/iResolution.y,-.4),.02),2.);"
   "return mix(i,y,step(1.,y.x));"
 "}"
 "vec2 scene1(vec3 v)"
 "{"
   "return v+=c.xyy*.05*t,vec2(v.z+.5-.5*mfsmoothstep_noise2d(v.xy,.9,1.,.1)+.05*mfsmoothstep_noise2d(v.xy,120.,180.,1.7),1.);"
 "}"
 "vec2 scene2(vec3 v)"
 "{"
   "v+=-13.*c.yxy+c.xxy*25.+c.yxy*.05*t;"
   "float x=-.5*mfsmoothstep_noise2d(v.xy,.91,2.,.1);"
   "if(v.z>-.19)"
     "x+=.05*mfsmoothstep_noise2d(v.xy,120.,180.,1.7);"
   "vec2 i=vec2(v.z+x,1.),y=vec2(v.z+.21-gerst(v.xy,22),2.);"
   "return mix(i,y,step(y.x,i.x));"
 "}"
 "vec2 scene3(vec3 v)"
 "{"
   "v+=c.yxy*.5*t;"
   "vec3 i=vec3(mod(v.x,2.)-1.,mod(v.y,2.)-1.,v.z),s=v-i;"
   "vec2 f=vec2(length(i.xy-.5*vec2(rand(s.xy),rand(s.xy*1.1)))-.1,1.),y=vec2(v.z-.2*mfsmoothstep_noise2d(v.xy,.9,1.,.1),1.);"
   "float x=-length(max(abs(i)-vec3(1.,2.,50.),0.));"
   "x=abs(x)+.4;"
   "f.x=min(f.x,x);"
   "return mix(y,f,step(f.x,y.x));"
 "}"
 "vec2 scene4(vec3 v)"
 "{"
   "vec3 i=v;"
   "v+=t*c.yxy;"
   "vec3 s=v;"
   "v=mod(v,1.)-.5;"
   "vec3 x=s-v;"
   "float d=length(x);"
   "vec3 y=.25*vec3(rand(d*c.xx),rand(3.*d*c.xx),rand(6.*d*c.xx));"
   "vec2 f=vec2(worm(c.yyy,vec3(.1*sin(5.*t+10.*rand(length(s-v)*c.xx)),0.,.1),.2*c.yyx,v-y),3.),r=vec2(length(v-y)-(.036+.01*mod(t,T)/T),4.),m=mix(f,r,step(r.x,f.x)),n=vec2(length(v-.2*c.yyx-y)-(.036+.01*mod(t,T)/T),4.);"
   "m=mix(m,n,step(n.x,m.x));"
   "float z=3.*acos(min(s.z,s.x)/length(s.xz));"
   "vec3 o=.5*vor(vec2(s.y+z,z));"
   "float e=o.x;"
   "vi=o.yz;"
   "f=vec2(abs(length(s.xz)-3.)-e,5.);"
   "m=mix(m,f,step(f.x,m.x));"
   "float l=-length(max(abs(v)-.5,0.));"
   "l=abs(l)+.1;"
   "m.x=min(m.x,l);"
   "return m;"
 "}"
 "vec2 scene(vec3 v)"
 "{"
   "if(t<20.)"
     "return scene1(v);"
   "else"
     " if(t<30.)"
       "return scene2(v);"
     "else"
       " if(t<40.)"
         "return scene3(v);"
       "else"
         " if(t<7000.)"
           "return scene4(v);"
 "}"
 "const float dx=.0001;"
 "vec3 normal(vec3 v)"
 "{"
   "float x=scene(v).x;"
   "return normalize(vec3(scene(v+dx*c.xyy).x-x,scene(v+dx*c.yxy).x-x,scene(v+dx*c.yyx).x-x));"
 "}"
 "vec3 bg(vec2 v)"
 "{"
   "if(t<20.)"
     "{"
       "v+=.01*t*c.yx;"
       "vec2 i=mod(v,.05)-.025,x=v-i;"
       "float s=.17*exp(-.2*t);"
       "return.15*c.xxx+mix(.4*c.xyy,.8*c.xxy,1.-2.*v.y-length(v))*exp(-.2*t)+c.xxx*smoothstep(s+.01,s-.01,length(v))+2.*tanh(.2*t)*smoothstep(.003,-.003,length(i-.02*vec2(rand(x),rand(.1*x+.1*c.xx)))-.002*rand(.1*x))*(.2*vec3(rand(.1*x),rand(.1*x+.1*c.xx),rand(x+.3*c.xx))+.8)+(.4+.2*mfsmoothstep_noise2d(v+cos(.5*t)*sin(.5*v.x)*sin(.6*v.y),2.5,100.,.55))*exp(-.05*t);"
     "}"
   "else"
     " return c.xxx;"
 "}"
 "float B(float v)"
 "{"
   "return smoothstep(v-2.,v-1.,iTime)*(1.-smoothstep(v+2.,v+3.,iTime));"
 "}"
 "void fore(out vec4 v,in vec2 x,float i)"
 "{"
   "t=i;"
   "vec2 f;"
   "vec3 y,s=.5+.5*mfsmoothstep_noise2d(c.yy,.9,1.,.1)-c.yxy+.5*c.yyx,m=.25*c.yyx,r=c.xyy,d=c.yyx,l=m+r*x.x+d*x.y,p=normalize(l-s);"
   "if(t>40.)"
     "s=-c.yxy,m=c.yyy;"
   "float a=0.,n=0.,o=0.,e=15.;"
   "int z=100;"
   "if(i>20.)"
     "e=55.;"
   "if(i>30.)"
     "e=50.,z=200;"
   "else"
     " if(i>40.)"
       "e=200.;"
   "for(int b=0;b<z;++b)"
     "{"
       "y=s+a*p;"
       "f=scene(y);"
       "if(f.x<.005)"
         "break;"
       "if(a>e||b==z-1)"
         "{"
           "v=vec4(bg(x),1.);"
           "return;"
         "}"
       "a+=f.x;"
     "}"
   "vec3 b=normal(y),g=c.yxy,w=y+c.yyx,u=normalize(y-s),h=normalize(reflect(-g,b)),R=normalize(reflect(-w,b)),B;"
   "if(f.y==1.)"
     "B=.01*c.xyy*dot(g,b)+.2*c.xxx*pow(abs(dot(h,u)),4.)+(.05*c.xyy+.05*c.yxy)*pow(abs(dot(h,u)),2.),B*=exp(-.2*iTime);"
   "else"
     " if(f.y==2.)"
       "B=.4*c.xxx*dot(w,b)+.2*c.xxx*pow(abs(dot(R,u)),2.);"
     "else"
       " if(f.y==3.)"
         "B=.6-(.8*c.yyx+.3*c.xyy)*dot(g,b)*mod(t,T)/T+.8*c.xxx*dot(g,b)+.2*c.xxx*pow(abs(dot(h,u)),4.)+(.05*c.xyy+.05*c.yxy)*pow(abs(dot(h,u)),2.);"
       "else"
         " if(f.y==4.)"
           "B=1.+.8*c.xxx*dot(g,b)+.2*c.xxx*pow(abs(dot(h,u)),4.)+(.05*c.yyx+.05*c.yyx)*pow(abs(dot(h,u)),2.);"
         "else"
           " if(f.y==5.)"
             "g=normalize(y),h=normalize(reflect(-g,b)),u=normalize(y-s),B=.6+.3*vec3(.75+.1*rand(vi),.75+.1*rand(2.*vi),.6+.4*rand(5.*vi))*dot(g,b)*mod(t,T)/T+.8*c.xxx*dot(g,b)+.05*c.xxx*pow(abs(dot(h,u)),2.);"
           "else"
             " B=c.yyy;"
   "if(i<20.)"
     "B=mix(B,.15*c.xxx,cosh(-2.*y.z)*tanh(.109*y.y));"
   "else"
     " if(i<40.)"
       "B=mix(B,c.xxx,tanh(.1*y.y));"
     "else"
       " if(i<7000.)"
         "B=mix(B,c.xxx,tanh(.08*y.y));"
   "v=vec4(B,1.);"
 "}"
 "void mainImage(out vec4 v,in vec2 x)"
 "{"
   "vec2 y=x/iResolution.yy-.5,f;"
   "vec4 i,s,m;"
   "fore(i,y,iTime);"
   "if(iTime<40.)"
     "fore(s,y,iTime+.01),v=.333*(i+s);"
   "else"
     " v=i;"
   "vec3 r=v.xyz;"
   "if(iTime<180.)"
     "{"
       "f=z10presents(y);"
       "float d=step(f.x,0.);"
       "if(f.y==1.)"
         "r=mix(r,mix(r,c.xxx,.1),d);"
     "}"
   "vec2 d=y+(.01*iTime-.12)*c.yx;"
   "float p=atan(abs(d.y/d.x)),e=length(d);"
   "r+=1.4*(.5+.25*sin(2.3*pi*p)+.25*sin(4.*pi*p)+.25*sin(1.5*pi*p))*exp(-3.*e)*c.xxx*exp(-.9*t)*(1.-smoothstep(1.4,1.6,iTime));"
   "float l=1.;"
   "v=vec4(r,1.);"
 "}"
 "void main()"
 "{"
   "mainImage(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
